[tools]
node = "24.0.2"
python = "3.13.3"
go = "1.24"
deno = "latest"
kind = "0.27.0"
bun = "latest"
kubectl = "1.33.1"
helmfile = "latest"
java = "corretto-24"
"pipx:poetry" = "latest"
pipx = "latest"
pnpm = "10.11.0"


