[tools]
node = "24.7.0"
python = "3.13.7"
go = "1.25"
deno = "latest"
kind = "0.30.0"
bun = "latest"
kubectl = "latest"
helmfile = "latest"
java = "corretto-24"
"pipx:poetry" = "latest"
pipx = "latest"
pnpm = "latest"
rust = "latest"
opentofu = "latest"
ast-grep = "latest"
lua = "5.4"
biome = "latest"
markdownlint-cli2 = "latest"
terraform = "latest"
tflint = "latest"
trivy = "latest"
dive = "latest"
helm = "latest"
uv = "latest"
cmctl = "latest"
kubeconform = "latest"
kubecm = "latest"
docker-cli = "latest"
docker-compose = "latest"
kubectx = "latest"
krew = "latest"
k9s = "latest"
jq = "latest"
azure-cli = "latest"
bat = "latest"
hcloud = "latest"
just = "latest"
ollama = "latest"
sops = "latest"
yq = "latest"
flux2 = "latest"
slsa-verifier = "latest"
cosign = "latest"
talosctl = "latest"
pulumi = "latest"
gh = "latest"
age = "latest"
eza = "latest"
hadolint = "latest"
lazygit = "latest"
nova = "latest"
pluto = "latest"
popeye = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
