apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: gitea-charts
  pass_credentials_all: false
  password: ""
  url: https://dl.gitea.com/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ingress-nginx
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: hcloud
  pass_credentials_all: false
  password: ""
  url: https://charts.hetzner.cloud
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: authelia
  pass_credentials_all: false
  password: ""
  url: https://charts.authelia.com
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kestra
  pass_credentials_all: false
  password: ""
  url: https://helm.kestra.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: gitlab
  pass_credentials_all: false
  password: ""
  url: https://charts.gitlab.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://traefik.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cnpg
  pass_credentials_all: false
  password: ""
  url: https://cloudnative-pg.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: schichtel
  pass_credentials_all: false
  password: ""
  url: https://schich.tel/helm-charts
  username: ""
