apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: gitea-charts
  pass_credentials_all: false
  password: ""
  url: https://dl.gitea.com/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ingress-nginx
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/ingress-nginx
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: hcloud
  pass_credentials_all: false
  password: ""
  url: https://charts.hetzner.cloud
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: authelia
  pass_credentials_all: false
  password: ""
  url: https://charts.authelia.com
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kestra
  pass_credentials_all: false
  password: ""
  url: https://helm.kestra.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: gitlab
  pass_credentials_all: false
  password: ""
  url: https://charts.gitlab.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://traefik.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cnpg
  pass_credentials_all: false
  password: ""
  url: https://cloudnative-pg.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: schichtel
  pass_credentials_all: false
  password: ""
  url: https://schich.tel/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: sonarqube
  pass_credentials_all: false
  password: ""
  url: https://SonarSource.github.io/helm-chart-sonarqube
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: schwarm
  pass_credentials_all: false
  password: UZ7B9&kJRCX&*!QAphM$wCaLLxDSJs4k
  url: https://nexus.schwarm-tech.com/repository/helmcharts-releases/
  username: diana.bendziula@schwarm.com
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: k8ssandra
  pass_credentials_all: false
  password: ""
  url: https://helm.k8ssandra.io/stable
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: hashicorp
  pass_credentials_all: false
  password: ""
  url: https://helm.releases.hashicorp.com
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami-legacy
  pass_credentials_all: false
  password: ""
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: schwarm-staging
  pass_credentials_all: false
  password: UZ7B9&kJRCX&*!QAphM$wCaLLxDSJs4k
  url: https://nexus.schwarm-tech.com/repository/helmcharts-staging/
  username: diana.bendziula@schwarm.com
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nvidia
  pass_credentials_all: false
  password: ""
  url: https://nvidia.github.io/k8s-device-plugin
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kedacore
  pass_credentials_all: false
  password: ""
  url: https://kedacore.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: wiz-sec
  pass_credentials_all: false
  password: ""
  url: https://charts.wiz.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: apache-airflow
  pass_credentials_all: false
  password: ""
  url: https://airflow.apache.org/
  username: ""
